### PR TITLE
Fix build for Haiku

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Came accross this when checking up latest Gwenview on Haiku.

**Comment by DamirPorobic** [comment]
Haiku doesn't need X11? What runs on Haiku?

**Comment by Begasus** [comment]
You got me there :) No we don't use X11 (xorg) on Haiku, my guess here is that Qt is all it really requires for Haiku.
For UI Haiku uses it's own API's (I'm not familiar enough there to comment on the insights). :)

**Comment by Begasus** [comment]
From some comments on IRC:
Haiku has its own display server protocol/app_server.

**Comment by Begasus** [comment]
On second thought, got the build completed with X11 enabled (we do have a libX11 port). Will get back after checking some things, if need be I'll close the PR.

**Comment by DamirPorobic** [comment]
Most of the stuff is done through Qt, that is true, but there are some things where we talk directly to the desktop/display manager and if there is no X11 or Wayland, there must be something other there that is unknwon to us and we cannot speak with it.

**Comment by Begasus** [comment]
I'm not familiar with the codebase for Haiku itself, but this probalby is done by the app_server/libbe. As it looks it seems this patch isn't needed, sorry about the noise. :)
Annotate

**Comment by Begasus** [comment]
Not required, thanks for looking into it though. 👍

**Comment by Begasus** [comment]
@DamirPorobic I just added kColorPicker to our packages, I'm in process of adding on for KImageAnnotator, but I can't find a good description for it, is there any information around for this?

**Comment by DamirPorobic** [comment]
This is all I have https://github.com/ksnip/kColorPicker

**Comment by Begasus** [comment]
kColorPicker is already fine: https://github.com/haikuports/haikuports/commit/8529c349f5d7fcb147f9ac94568262389fb04bb1
Just need some information to fill in the gaps for DESCRIPTION in the recipe for kImageAnnotator (like is done in the one for kColorPicker). :)

**Pull request closed without merging**
