### PR TITLE
Add new tool to create duplicates

### PR DESCRIPTION
**Pull request by fnkabit**
Issue #131 

## Work in progress
Works fine.

Need to decide on:
* selection color
* tool icon

### CODE REVIEW

**Review by DamirPorobic — APPROVED** [review]

**Comment by DamirPorobic** [comment]
Would it have been possible to implement this in a way like the Blur or Pixelate tool? Those tools access the parent scene and get whats behind them and then do some additional magic. In your case here you could also access the scene to get the region that you want to duplicate but only as long as you're initially drawing the rect, when finished, you could remember the region where the tool was drawn an repaint that where you want. The good side of this approach is that you can encapsulate all the tool logic in the tool itself and don't need to pollute the annotationArea.

**Comment by fnkabit** [comment]
@DamirPorobic I will do something similar to the pixelate tool.

**Comment by fnkabit** [comment]
Reworked duplicate tool.

**Comment by DamirPorobic** [comment]
Nice, much cleaner I would say if you implement it like this.

Regarding the properties stuff you were setting, usually properties are set either through config or in the propertiesFactory so that items don't know anything about it. I have refactored that part.

**Comment by fabianski7** [comment]
I just made the build of ksnip from master just to use this. it is very useful!
I found a small bug only when the Grayscale effect is applied. The part that was duplicated still has colors.

**Comment by DamirPorobic** [comment]
Nice catch, I'll log a bug for it.

**Pull request merged**
