### PR TITLE
Add KDE support for scale factor

### PR DESCRIPTION
**Pull request by precla**
As the title says :)

is `char` (g, k, ... ) ok?

### CODE REVIEW

**Comment by DamirPorobic** [comment]
Sorry for the delay, I'm currently not getting much time for my open source projects. I think we should use an enum for that with `KDE`, `Gnome` and `Unknown` values. Also, the logic now that I look at it seem to be wrong in this place, we should exract this method into some helper class that can be reused. If you want I can do this change.

**Comment by precla** [comment]
Indeed, `enum` sounds better.
You mean the logic inside `getScaleFactor`?

**Comment by DamirPorobic** [comment]
I mean the logic in `getLinuxDesktopEnvironment`

**Comment by DamirPorobic** [comment]
Thanks for provindg the PR! I'll change the enums and the helper class on master

**Pull request merged**
