### PR TITLE
Implemented zoom by wheel for more precise annotations

### PR DESCRIPTION
**Pull request by fpohtmeh-github**
Scale range is 100%-800%

### CODE REVIEW

**Comment by DamirPorobic** [comment]
Thanks for providing this feature, probably a lot of people are waiting for this one and it was on top of my list. Works nice as expected though two things are unexpected: 
1. Wheel forward zooms out (makes the image smaller) and backward zooms in (makes the image larger). I was expecting the opposite like in Inkscape or Gimp. 
2. Resize handles are scaled too because they are also items in the Scene. It would be nice if they could stay always the same size though this might be more difficult to achieve, maybe by scaling individual items. If this is to much we log a technical dept item and leave it for future releases.

One think would be nice to have:
1. Some indicator at what zoom level we are. Maybe we could overwrite the render Method of the view and write with overlay text what the current zoom level is and what size in px the image currently has in the bottom right corner. 

Regarding the code:
1. Can you please use auto for variable definition, keeps the code more readable and is consistent with the rest of the application.
2. Please rename the method `zoom(double factor, const QPoint &viewPoint)` to something like `zoomToPoint`. I try to rename methods as descriptive as possible and I try to avoid method with same name and different signature.
3. Is it possible to extract the zoom logic to its own class? That will make it easier to test this functionality with unit tests. 
4. Add unit tests.  

Sorry for the many points, if you want I can take care of some of them when I get some time. I'm planning this feature for `0.4.0`

**Comment by fpohtmeh-github** [comment]
1. Ok, I'll swap zoom directions
2. I'll find the practical way to scale handles. Probably in the initial version of zoom feature we can leave this bug.

Zoom indicator. I'll definitely add this indicator to Qt widgets UI, not graphics scene. In graphics scene it can cover valuable information, so it's not the option.

Ok, I'll refine the code. If you have ideas what to check in unit tests for this feature, please let me know.

**Comment by DamirPorobic** [comment]
Thanks, regarding the Unit Test, nothing special, just for input factor X you expect the scale call with values Y and Z. And maybe one when scaling was done previously. Just something to ensure everything works as you wrote it in case somebody touches that code part in future.

**Comment by fpohtmeh-github** [comment]
@DamirPorobic, I pushed most changes and this note is explanation for them. Probably you have some ideas and I will include them into the final step.
- I added classes AbstractCamera and AnnotationViewCamera to handle views manipulation. Currently they handle zoom routines only, but in future I expect to encapsulate view rotation/translation there.
- Handles are automatically scaled after zooming :).
- I didn't add zoom controls to UI. I'll open another issue to discuss this.
- Zoom range is limited by range 100%-800%. I'll add smaller values in UI phase because in current workflow it's hard to get 100% back after zooming out.
- Unit Tests are under development now. I'll check existing tests covering as well.

**Comment by DamirPorobic** [comment]
Sorry for the delay, I was busy with some personal stuff last week, I hope I will be able to review this soon. 

Regarding the UI part, been thinking about it, we probably need some controls to do the zoom there too, not only to visualize the current zoom level. There are users using only touchpad or have currently no mouse available, those wouldn't be able to zoom with wheel.

**Comment by DamirPorobic** [comment]
Regarding the naming, would ViewPort be a better name instead of camera? Also, we have methods in resize Handles that contain Zoom, but for them it's just scaling or changing size. Shouldn't the handles have only a setSize methods?

**Comment by DamirPorobic** [comment]
Merged

**Comment by fpohtmeh-github** [comment]
@DamirPorobic great, I wish I'll find more time to contribute here.
BTW, I see that Spectacle now uses your image annotator. Congrats! ;)

**Comment by fpohtmeh-github** [comment]
> Regarding the naming, would ViewPort be a better name instead of camera? Also, we have methods in resize Handles that contain Zoom, but for them it's just scaling or changing size. Shouldn't the handles have only a setSize methods?
> 
> If that's ok with you I can do the changes and I think I would merge it. The UI Part we can do in a separate issue.

Camera refers to classical camera definition from 2D/3D frameworks. Using camera you can zoom, pan and rotate scene.
Camera defines the viewer position, while viewport limits visible region of scene. Do you think it can be useful to rotate scene in annotator?

Well, ResizeHandle can have method setSize. Personally for me applyZoomValue also looks fine, because it shows that component reacts on zoom changes and encapsulates the resizing logic. Looking ahead, we can separate some interface Zoomable with single method applyZoomValue to zoom more components in future.

**Comment by DamirPorobic** [comment]
> @DamirPorobic great, I wish I'll find more time to contribute here.

Your contibution is very welcome here, whenever you find time. There are enoguh features :) 

> BTW, I see that Spectacle now uses your image annotator. Congrats! ;)

Thanks, that was actually the reason for extracting the annotation part into a stand-alone library. 

> Do you think it can be useful to rotate scene in annotator?

Can't think of a feature that requires that at the moment, but you never know.

> Well, ResizeHandle can have method setSize. Personally for me applyZoomValue also looks fine, because it shows that component reacts on zoom changes and encapsulates the resizing logic. Looking ahead, we can separate some interface Zoomable with single method applyZoomValue to zoom more components in future.

Yes, I have left it for now as it was, in future a separate interface would be nice I guess.

**Pull request merged**
