### PR TITLE
Draw point when clicking and releasing without moving cursor

### PR DESCRIPTION
**Pull request by fpohtmeh-github**
Path had a visual artifact at the beginning

### CODE REVIEW

**Comment by DamirPorobic** [comment]
A specific reason why you're removing this part?

**Comment by fpohtmeh-github** [comment]
> A specific reason why you're removing this part?

Every path has the same beginning (0; 0) -> (1; 1). It's quite obvious thing when I draw horizontal or vertical lines.
This hardcoded segment looks even worse if I add zooming in another branch.

It's better to move to startPosition then line to startPosition to get point.

**Comment by DamirPorobic** [comment]
> Opposite question: why do you need that (1; 1)? :)

Glad you asked xD
The only reason for that part being there is that when you click on the AnnotationArea and release without moving the mouse cursor, you get an invisible path. It's there, you can select it, resize, move, but it's not visible as the painter doesn't draw paths with 0 length. A clean solution would be to check for paths with 0 length and draw a dot instead in this special case.

**Comment by fpohtmeh-github** [comment]
(0; 0) - (1; 1) is a dirty hack.
Drawing of point with diameter that's equal to line width is the correct solution. I can implement that

**Comment by DamirPorobic** [comment]
Yeap, that would be the correct solution. Thanks.

**Comment by DamirPorobic** [comment]
Merged, thanks for providing the PR.

**Pull request merged**
