### PR TITLE
Switch to tab before displaying save prompt

### PR DESCRIPTION
**Pull request by fnkhz**
Implements: https://github.com/ksnip/ksnip/issues/750

### CODE REVIEW

**Review by DamirPorobic — APPROVED** [review]

**Comment by DamirPorobic** [comment]
Thanks for providing this PR!

**Comment by DamirPorobic** [comment]
@fnkhz have you tested this in ksnip? Doesn't seem to work for me. I have several open unsaved tabs, I right click on one that is not active and select "Close", I get the prompt to confirm save or close but the tab is not activated, it's still in the background.

**Comment by fnkhz** [comment]
@DamirPorobic It works for the "Close All", "Close Other", "Close All to the Left", "Close All to the Right" context menu options. Forgot to implement for the basic "Close" option; doing that now.

**Comment by DamirPorobic** [comment]
@fnkhz that was the first I've tested xD

Another question, wasn't it possible to implement this from ksnip so we activate only when saving? Now we are always activating the tab, even if we don't save. I haven't looked in the code though.

**Comment by fnkhz** [comment]
@DamirPorobic Thought it would be better to see the image before deciding if you want to save or not.

**Comment by DamirPorobic** [comment]
Yes, that is true of course, but there is also the "Don't ask" options, which for example is always on for me. I never get the "Do you want to save this", it just closes everything. But from your response I guess you didn't check, it's ok.

**Comment by fnkhz** [comment]
> 

You are right, I wasn't aware of the "Don't ask" option. Will make a PR today to address this.

**Comment by DamirPorobic** [comment]
> A bit offtopic, but maybe it would be a good idea to have some "yes to all" and "no to all" buttons displayed when there are multiple images to be closed.

Definitely, there might be even a feature request for it, if not, then we should open one.

**Comment by fnkhz** [comment]
> > A bit offtopic, but maybe it would be a good idea to have some "yes to all" and "no to all" buttons displayed when there are multiple images to be closed.
> 
> Definitely, there might be even a feature request for it, if not, then we should open one.

Thanks, will open the feature request as well, before making the PR.

**Comment by DamirPorobic** [comment]
> You are right, I wasn't aware of the "Don't ask" option. Will make a PR today to address this.

It's an edge case, no worries about it. If you want to move it all together to ksnip, fine, if not, you can leave it as it is.

**Comment by DamirPorobic** [comment]
Oh, another of topic, are you Ștefan xD?

**Comment by fnkhz** [comment]
> Oh, another of topic, are you Ștefan xD?

Oh no, you have revealed my identity to the Internets ! :grin: 
Yes it's me; some people do distro hopping, apparently I do username hopping  :smile:

**Comment by DamirPorobic** [comment]
The hop was not that far to be honest xD
You had me worried a bit since you stopped committing suddenly last year. Glad you're back :)

**Comment by fnkhz** [comment]
> The hop was not that far to be honest xD You had me worried a bit since you stopped committing suddenly last year. Glad you're back :)

Thank you, glad to be back !

**Pull request merged**
