### PR TITLE
Move zoom indicator to config panel

### PR DESCRIPTION
**Pull request by fnkabit**
Issue: #157 

image

### CODE REVIEW

**Comment by DamirPorobic** [comment]
Maybe the buttons could be hidden with `setButtonSymbols(QAbstractSpinBox::NoButtons)`
And a percent suffix would be nice `setSuffix(QLatin1Literal("%"))`

**Comment by fnkabit** [comment]
@DamirPorobic It does look better now, thanks.

image

**Comment by DamirPorobic** [comment]
yes, but the gray text is indeed a bit irritating. Is there an option to make it readOnly instead of disabled? Does it make the tet more readable?

**Comment by fnkabit** [comment]
> yes, but the gray text is indeed a bit irritating. Is there an option to make it readOnly instead of disabled? Does it make the tet more readable?

This would be readonly.
image

**Comment by DamirPorobic** [comment]
Looks better I think. 

What do you say?  Looks ok or would you try something else?

**Comment by fnkabit** [comment]
I think it looks ok, yes.

**Comment by DamirPorobic** [comment]
I've added handling for changing tabs, the zoom value was not updated when you switched to another tab. Also I've added an icon and created a widget called zoomIndicator that just wraps the label and spinbox.

**Pull request merged**
